version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Patience123@
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=Patience123@
      - DB_NAME=postgres
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis
    restart: always

  redis:
    image: redis:alpine
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "8099:80"
    depends_on:
      - backend
    restart: always

volumes:
  pgdata:
